org: techdias
service: adegaTech

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient
package:
  individually: true

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool
    UserPoolId: ${self:service}-${self:provider.stage}.UserPoolId}

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}
  - ${file(./sls/functions/category.yml)}
  - ${file(./sls/functions/product.yml)}
resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/ProductsBucket.yml)}
