createProduct:
  handler: src/main/functions/product/createProduct.handler
  events:
    - httpApi:
        path: /product
        method: POST
        authorizer:
          name: CognitoAuthorizer
listProducts:
  handler: src/main/functions/product/listProducts.handler
  events:
    - httpApi:
        path: /products
        method: GET
        authorizer:
          name: CognitoAuthorizer
getProductById:
  handler: src/main/functions/product/getProductById.handler
  events:
    - httpApi:
        path: /products/{productId}
        method: GET
        authorizer:
          name: CognitoAuthorizer
