export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN ',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NAME_ALREADY_IN_USE = 'NAME_ALREADY_IN_USE',
  //HTTP
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  PRODUCT_NAME_ALREADY_IN_USE = 'PRODUCT_NAME_ALREADY_IN_USE'
}
