statements:
  - Effect: Allow
    Action: cognito-idp:AdminDeleteUser
    Resource: !GetAtt UserPool.Arn
  - Effect: Allow
    Action: s3:PutObject
    Resource: !Sub '${ProductsBucket.Arn}/*'
  - Effect: Allow
    Action: s3:PutObject
    Resource: !Sub '${CategoryBucket.Arn}/*'
  - Effect: Allow
    Action: s3:DeleteObject
    Resource: !Sub '${ProductsBucket.Arn}/*'
